version: '3'

services:
    deadlinewbs:
        container_name: DeadlineWBS

        image: deadline-client
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.1.3

        volumes:
            - /opt/Thinkbox/DeadlineRepository10:/mnt/DeadlineRepository10

        environment:
            TZ: "Asia/Shanghai"

        ports:
            - '8081:8081'

        entrypoint:
            ['./deadlinewebservice']
            
networks:
    extnetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
